version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    container_name: hello-node-app

  python-app:
    build: ./python-app
    ports:
      - "5000:5000"
    container_name: hello-python-app
